services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev_system_app
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=/app/config/config.json
    depends_on:
      - db
    networks:
      - dev_system_network
    command: ["/bin/sh", "-c", "until nc -z db 5432; do echo 'Waiting for DB...'; sleep 1; done; ./main"]

  db:
    image: postgres:latest
    container_name: dev_system_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: development_system
    ports:
      - "5433:5432"
    networks:
      - dev_system_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

networks:
  dev_system_network:
    driver: bridge

volumes:
  postgres_data: