basePath: /
definitions:
  handler.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  models.Competency:
    properties:
      name:
        type: string
      description:
        type: string
      parent_id:
        type: integer
    type: object
  models.Material:
    properties:
      title:
        type: string
      description:
        type: string
      content:
        type: string
      type:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: alexandernoskov.dev@gmail.com
    name: API Support
  description: Это пример API сервера для системы развития сотрудников под названием
    «Компетентум».
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: devSystem API Документация
  version: "1.0"
paths:
  /competencies:
    get:
      consumes:
      - application/json
      description: Получение списка с компетенциями.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Competency'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Получить все компетенции
      tags:
      - competencies
    post:
      consumes:
      - application/json
      description: Создает новую компетенцию по входным данным.
      parameters:
      - description: Входные данные
        in: body
        name: competency
        required: true
        schema:
          $ref: '#/definitions/models.Competency'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Competency'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Создать компетенцию
      tags:
      - competencies
  /competencies/{id}:
    delete:
      consumes:
      - application/json
      description: Удаление компетенции по её ID.
      parameters:
      - description: ID компетенции
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Удалить компетенцию
      tags:
      - competencies
    put:
      consumes:
      - application/json
      description: Обновление сведений о компетенции по её ID.
      parameters:
      - description: ID компетенции
        in: path
        name: id
        required: true
        type: integer
      - description: Входные данные
        in: body
        name: competency
        required: true
        schema:
          $ref: '#/definitions/models.Competency'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Competency'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Обновить компетенцию
      tags:
      - competencies
  /materials:
    get:
      consumes:
      - application/json
      description: Получение списка со всеми материалами.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Material'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Получить все материалы
      tags:
      - materials
    post:
      consumes:
      - application/json
      description: Создание нового материала по входным данным.
      parameters:
      - description: Входные данные
        in: body
        name: material
        required: true
        schema:
          $ref: '#/definitions/models.Material'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Material'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Создать материал
      tags:
      - materials
  /materials/{id}:
    delete:
      consumes:
      - application/json
      description: Удаление материала по его ID.
      parameters:
      - description: ID материала
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Удалить материал
      tags:
      - materials
    get:
      consumes:
      - application/json
      description: Получение сведений о материале по его ID.
      parameters:
      - description: ID материала
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Material'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Получить материал по ID
      tags:
      - materials
    put:
      consumes:
      - application/json
      description: Обновление материала по его ID.
      parameters:
      - description: ID материала
        in: path
        name: id
        required: true
        type: integer
      - description: Входные данные
        in: body
        name: material
        required: true
        schema:
          $ref: '#/definitions/models.Material'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Material'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Обновить материал
      tags:
      - materials
swagger: "2.0"
